config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :teams
  resources :seasons
  resources :players
  resources :player_performance
  get "/about", to: "about#index"
  get 'search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :team_players
  has_many :teams, through: :team_players

  has_many :player_performances
  has_many :seasons, through: :player_performances

  validates :lastName, :skaterFullName, :positionCode, :shootsCatches, presence: true
end

app/models/player_performance.rb
class PlayerPerformance < ApplicationRecord
  belongs_to :player
  belongs_to :season

  validates :evGoals, :evPoints, :gameWinningGoals, :gamesPlayed, :goals, :otGoals, :penaltyMinutes, :plusMinus, :points, :ppGoals, :ppPoints, :shGoals, :shots, numericality: { only_integers: true }
  validates :pointsPerGame, :shootingPct, :timeOnIcePerGame, numericality: true
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :player_performances
  has_many :players, through: :player_performances

  validates :years, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_players
  has_many :players, through: :team_players

  validates :teamAbbrevs, presence: true, uniqueness: true
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @players = PlayerPerformance.all.limit(10)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
    @performances = PlayerPerformance.where(:player_id => params[:id])
    @teams = TeamPlayer.where(:player_id => params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @query = params[:query]
    @category = params[:team]

    if @query.blank?
      flash[:alert] = "Please enter a player's name."
      redirect_to search_path
    else
      if @category.blank?
        @results = Player.where("skaterFullName LIKE ?", "%#{sanitize_sql_like(@query)}%")

        if @results.empty?
          flash[:notice] = "No results found."
        end
      else
        # Finds all team players by the provided team id to narrow down the search
        team_players = TeamPlayer.where(team_id: @category["id"])

        # Searches through the team players list to find any Players who match the query
        @results = Player.joins(:team_players)
                        .where(team_players: { id: team_players })
                        .where("skaterFullName LIKE ?", "%#{sanitize_sql_like(@query)}%")

        if @results.empty?
          flash[:notice] = "No results found."
        end
      end
    end
  end

  private

  def sanitize_sql_like(str)
    ActiveRecord::Base.sanitize_sql_like(str)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @players = TeamPlayer.where(:team_id => params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/player_performance_helper.rb
module PlayerPerformanceHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_header.html.erb
<div class="nav_bar">
    <nav>

    <ul class="nav-list">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Teams', teams_path %></li>
      <li><%= link_to 'Players', player_performance_index_path %></li>
      <li>
        <div class="nav-search">
          <%= form_tag search_path, method: :get do %>
            <% # Added a category select to find player by the team selected %>
            <%= collection_select :team, :id, @search_categories, :id, :teamAbbrevs, { include_blank: 'All' }, { class: 'form-control' } %>
            <%= text_field_tag :query, params[:query] %>
            <%= submit_tag "Search" %>
          <% end %>
        </div>
      </li>
    </ul>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HockeyPlayersOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% # Renders a partial for header instead of being in-line within the application.html.erb page %>
    <%= render partial: "layouts/header" %>

    <%= yield %>

  </body>
</html>